name: Create resources using Terraform on GCP
 
on:

  push:

    branches:

      - main
 
jobs:

  terraform-gcp:

    runs-on: self-hosted
 
    steps:

      # Checkout Repository

      - name: Check out Git Repository

        uses: actions/checkout@v3
 
      # Debug Directory Structure

      - name: Debug Directory

        run: |

          echo "Working directory structure:"

          ls -la ${{ github.workspace }}
 
      # Cache TFLint plugins directory

      - name: Cache TFLint plugins directory

        uses: actions/cache@v2

        with:

          path: ~/.tflint.d/plugins

          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
 
      # Set up TFLint

      - name: Setup TFLint

        uses: terraform-linters/setup-tflint@v2

        with:

          github_token: ${{ secrets.GKE_GITHUB_TOKEN }}
 
      # Print TFLint version

      - name: Show TFLint version

        run: tflint --version
 
      # Initialize TFLint plugins

      - name: Initialize TFLint

        run: tflint --init
 
      # Run TFLint checks recursively in all directories

      - name: Run TFLint

        run: tflint -f compact --recursive --force
 
      # Install Terraform

      - name: Install Terraform

        run: |

          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

          sudo apt update || true

          sudo apt install -y terraform || echo "Terraform installation failed"
 
      # Authenticate via SAKE

      - name: 'Authenticate via SAKE'

        uses: 'google-github-actions/auth@v2'

        with:

          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
 
      # Verify credentials path

      - name: Verify Credentials Path

        run: |

          echo "Checking credentials file:"

          ls -la /home/urolime/actions-runner/_work/GCP-POC/GCP-POC/
 
      # Initialize Terraform

      - name: Terraform Init

        working-directory: ./GKE_DevSecops

        env:

          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        run: terraform init
 
      # Format Terraform files

      - name: Terraform Format

        working-directory: ./GKE_DevSecops

        run: terraform fmt
 
      # Run Terraform lint checks

      - name: Terraform Lint

        working-directory: ./GCP-POC/GKE_DevSecops

        run: tflint
 
      # Generate Terraform execution plan

      - name: Terraform Plan

        working-directory: ./GCP-POC/GKE_DevSecops

        env:

          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        run: terraform plan
 
      # Apply Terraform configuration

      - name: Terraform Apply

        working-directory: ./GCP-POC/GKE_DevSecops

        env:

          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        run: terraform apply -auto-approve -input=false
 
      # Optional: Destroy resources

      - name: Terraform Destroy

        if: always()

        working-directory: ./GCP-POC/GKE_DevSecops

        env:

          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        run: terraform destroy -auto-approve -input=false

 
